version: "3.8"
services:
  redis: 
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mongo-network
  mongodb:
    image: mongo
    container_name: mongodb-replicaset-1-node
    ports:
      - 27017:27017
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 30s
      retries: 3
    command: mongod --port 27017 --replSet rs0 --bind_ip_all

volumes:
  mongo-data:


networks:
  mongo-network:
    driver: bridge
